on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "*"
            - run: npm update

            # Validate code.
            - run: npm run check
